services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SECRET_KEY: ${SECRET_KEY}
        DB_HOST: ${DB_HOST}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PORT: ${DB_PORT}
        DB_PASS: ${DB_PASS}
    container_name: film-store
    environment:
      DB_HOST: film-database
      REDIS_HOST: redis://film-redis:6379
      PYTHONUNBUFFERED: 1
    ports:
      - "8000:8000"