services:
  web:
    image: python:latest
    container_name: film-store
    env_file: .env
    environment:
      DB_HOST: film-database
      PYTHONUNBUFFERED: 1
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - database
    command: sh -c "pip install -r requirements.txt && python film_store/manage.py migrate && python film_store/manage.py runserver 0.0.0.0:8000"

  database:
    image: postgres:14-alpine
    container_name: film-database
    ports:
      - "5432:5432"
    env_file: .env
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: 5s
      timeout: 5s
      retries: 5