services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: film-store
    env_file: .env
    environment:
      DB_HOST: film-database
      PYTHONUNBUFFERED: 1
      DEBUG: True
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - ./:/app
    command: sh -c "python film_store/manage.py tailwind build && python film_store/manage.py collectstatic --noinput && python film_store/manage.py makemigrations && python film_store/manage.py migrate && python film_store/manage.py create_superuser_if_not_exists && python film_store/manage.py runserver 0.0.0.0:8000"

      
  database:
    image: postgres:14-alpine
    container_name: film-database
    ports:
      - "5432:5432"
    env_file: .env
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: 5s
      timeout: 5s
      retries: 5