# Generated by Django 5.0.7 on 2024-08-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_generaluser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaluser',
            name='films',
            field=models.ManyToManyField(to='app.film'),
        ),
    ]
