# Generated by Django 5.0.7 on 2024-08-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_generaluser_films'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='cover_image_url',
        ),
        migrations.RemoveField(
            model_name='film',
            name='video_url',
        ),
        migrations.AddField(
            model_name='film',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='film',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
