# Generated by Django 5.0.7 on 2024-08-06 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_film_cover_image_url_remove_film_video_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generaluser',
            old_name='films',
            new_name='bought_films',
        ),
        migrations.AddField(
            model_name='generaluser',
            name='wishlist_films',
            field=models.ManyToManyField(related_name='wishlist', to='app.film'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
