# Generated by Django 5.0.7 on 2024-08-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaluser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
